### ISSUE TITLE
Regarding the Google Cloud API

### ISSUE THREAD

**Issue by GuptajiRocks** [NikhilSai5/Automated-Podcast#1]
Hi Nikhil, 
I forked the repo and was trying to tweak some functionalities of my own, but the API wasn't working.

Can you provide an idea on how to set up the API for personal use, as I guess the codebase currently is familiar with your credentials only.

**Comment by NikhilSai5** [comment]
yeah i use the openAI API and google cloud API,
for google cloud api you have to create a google cloud account and in it
you have to enable the api for "cloud storage" and "cloud text-to-speech
api"

**Comment by GuptajiRocks** [comment]
Okay, Thanks, will try.

Cheers!
